// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_cNCI-kj4F6W_TG51eVbxg1khP9x9TE0',
    appId: '1:1094810746512:web:269f76ba72dceea773e215',
    messagingSenderId: '1094810746512',
    projectId: 'imagine-16c70',
    authDomain: 'imagine-16c70.firebaseapp.com',
    storageBucket: 'imagine-16c70.appspot.com',
    measurementId: 'G-8P0YD3HSWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAGmMVFvEO73X7ulbqA5yAnq4hRWluftY',
    appId: '1:1094810746512:android:071317f231b5214773e215',
    messagingSenderId: '1094810746512',
    projectId: 'imagine-16c70',
    storageBucket: 'imagine-16c70.appspot.com',
  );
}
